version: "3.8"

services:
  go_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: golang-gateway:latest
    ports:
      - "8080:80"
    volumes:
      - ./templates:/root/templates
      - ./logs/gateway:/var/log/gateway
    environment:
      - GATEWAY_USER=admin
      - GATEWAY_PASS=C4lv0kkk
      - GATEWAY_JWT_SECRET=chaveUltraSeguraAqui
    depends_on:
      - health_service
      - secure_service
      - clock_service

  health_service:
    build:
      context: ./services/health_service
      dockerfile: Dockerfile
    image: golang-health_service:latest
    ports:
      - "8000:8000"

  secure_service:
    build:
      context: ./services/secure_service
      dockerfile: Dockerfile
    image: golang-secure_service:latest
    ports:
      - "9000:9000"

  clock_service:
    build:
      context: ./services/clock_service
      dockerfile: Dockerfile
    image: golang-clock_service:latest
    ports:
      - "9001:9001"
