version: "3.8"

services:
  go_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: golang-gateway:latest
    ports:
      - "8080:80"
    volumes:
      - ./templates:/root/templates
      - ./logs/gateway:/var/log/gateway
    depends_on:
      - health_service

  health_service:
    build:
      context: ./services/health_service
      dockerfile: Dockerfile
    image: golang-health_service:latest
    ports:
      - "8000:8000"
