# docker-compose.yml

version: "3.8"

services:
  go_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: golang-gateway:latest
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/root/templates
      - ./logs/gateway:/var/log/gateway
    env_file:
      - .env
    environment:
      - GATEWAY_JWT_SECRET=C4lv0kkk
    depends_on:
      - health_service
      - clock_service

  health_service:
    build:
      context: ./services/health_service
      dockerfile: Dockerfile
    image: golang-health_service:latest
    ports:
      - "8000:8000"

  clock_service:
    build:
      context: ./services/clock_service
      dockerfile: Dockerfile
    image: golang-clock_service:latest
    ports:
      - "9001:9001"