version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: go_gateway
    ports:
    - 8080:80
    depends_on:
    - health_service
    - echo_service
  health_service:
    build:
      context: ./services/health_service
      dockerfile: Dockerfile
    container_name: health_service
    ports:
    - 8000:8000
  echo_service:
    build:
      context: ./services/echo_service
      dockerfile: Dockerfile
    container_name: echo_service
    ports:
    - 9000:9000
