services:
  - route: /health
    target: http://health_service:8000
    log: /var/log/gateway/health/health.log

  - route: /clock
    target: ws://clock_service:9001
    log: /var/log/gateway/clock/clock.log

  - route: /template_health
    templateDir: /root/templates/template_health
    templateRoutes:
      contato: contact.html
      sobre: about.html
    log: /var/log/gateway/template_health/template_health.log
    login: true
    session_duration: 3600