
services:
  - route: /health
    target: http://health_service:8000
    log: /var/log/gateway/health

  - route: /template_health
    templateDir: /root/templates/template_health
    log: /var/log/gateway/template_health